
var BlackLivesMatter = [
  {"username":"GLaurajeanne64","realname":"#LauraJeanne4Trump","location":"USA...Florida and Connecticut","hashtags":[{"indices":[75,92],"text":"BlackLivesMatter"},{"indices":[93,108],"text":"HillaryClinton"},{"indices":[109,121],"text":"BarackObama"},{"indices":[122,132],"text":"Democrats"}],"likes":47969,"followers":15091},
  {"username":"Mr_SAP75","realname":"Yup.","location":"","hashtags":[{"indices":[114,131],"text":"BlackLivesMatter"}],"likes":6624,"followers":139},
  {"username":"Lochy_D","realname":"Lochy Denke","location":"Melbourne, Victoria","hashtags":[{"indices":[59,76],"text":"BlackLivesMatter"}],"likes":5652,"followers":100},
  {"username":"lindas106","realname":"lovingmyplanet","location":"","hashtags":[{"indices":[50,67],"text":"BlackLivesMatter"},{"indices":[68,79],"text":"LoveIsLove"},{"indices":[80,94],"text":"ScienceIsReal"},{"indices":[95,122],"text":"WomensRightsAreHumanRights"}],"likes":18111,"followers":403},
  {"username":"susan_dolly","realname":"Susan Philpott","location":"","hashtags":[{"indices":[73,81],"text":"Georgia"},{"indices":[82,99],"text":"BlackLivesMatter"}],"likes":1644,"followers":37},
  {"username":"susan_dolly","realname":"Susan Philpott","location":"","hashtags":[{"indices":[70,76],"text":"Texas"},{"indices":[77,94],"text":"BlackLivesMatter"}],"likes":1644,"followers":37},
  {"username":"jdp021189","realname":"Jerry Prince","location":"Midwest, Indiana","hashtags":[{"indices":[19,26],"text":"Bishop"},{"indices":[61,70],"text":"powerful"},{"indices":[83,87],"text":"BLM"},{"indices":[112,129],"text":"BlackLivesMatter"}],"likes":105000,"followers":7187},
  {"username":"robbipl","realname":"Paul/Pablo","location":"Pennsylvania, USA","hashtags":[{"indices":[19,36],"text":"BlackLivesMatter"}],"likes":8532,"followers":3439},
  {"username":"theangrybaptist","realname":"Angry Baptist","location":"","hashtags":[{"indices":[29,46],"text":"blacklivesmatter"}],"likes":58,"followers":6},
  {"username":"michaelwbunner","realname":"Michael W. Bunner","location":"Norristown, PA","hashtags":[{"indices":[12,18],"text":"Obama"},{"indices":[20,29],"text":"Sharpton"},{"indices":[31,41],"text":"RepWilson"},{"indices":[43,60],"text":"BlackLivesMatter"},{"indices":[74,78],"text":"CNN"},{"indices":[83,89],"text":"MSNBC"},{"indices":[121,130],"text":"racecard"}],"likes":734,"followers":153},
  {"username":"Cancun01702935","realname":"Cancun","location":"","hashtags":[{"indices":[98,115],"text":"Blacklivesmatter"}],"likes":216,"followers":9},{"username":"madyell0wbid","realname":"Isabel","location":"St Louis, MO","hashtags":[{"indices":[69,80],"text":"STLVerdict"},{"indices":[81,90],"text":"ExpectUs"},{"indices":[91,108],"text":"BlackLivesMatter"}],"likes":79,"followers":5}]
